-- DROP DATABASE DB_CAMAX;

CREATE DATABASE IF NOT EXISTS DB_CAMAX;

USE DB_CAMAX;


CREATE TABLE USUARIO (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TELEFONE INT NOT NULL,
    ADM BOOLEAN NOT NULL,
    ATIVO BOOLEAN NOT NULL
);

CREATE TABLE BRINQUEDO (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(150) NOT NULL, 
    QTD_EM_ESTOQUE INT NOT NULL,
    VALOR_DIARIA DOUBLE NOT NULL
);

CREATE TABLE FRETE (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(150) NOT NULL,
    VALOR DOUBLE NOT NULL
);

CREATE TABLE ENDERECO (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
    CEP INT NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    LOTE VARCHAR(100) NOT NULL,
    NUMERO INT NOT NULL,
    COMPLEMENTO VARCHAR(100) NOT NULL,
    REFERENCIAS VARCHAR(150) NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE ALUGUEL (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_FRETE INT NOT NULL,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    DATA_DEVOLUCAO_DEFINITIVA DATE NOT NULL,
    VALOR_TOTAL DOUBLE NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_FRETE) REFERENCES FRETE(ID)
);

CREATE TABLE ITEM (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_ALUGUEL INT NOT NULL,
    ID_BRINQUEDO INT NOT NULL,
    ALUGADO BOOLEAN NOT NULL,
    FOREIGN KEY (ID_ALUGUEL) REFERENCES ALUGUEL(ID),
    FOREIGN KEY (ID_BRINQUEDO ) REFERENCES BRINQUEDO(ID)
);

